[package]
name = "redact"
version = "0.1.0"
edition = "2021"
description = "Wrapper to avoid accidentally leaking sensitive data during printing/logging"
repository = "https://github.com/jeremyschiemann/redact.git"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
